apiVersion: v1
kind: Namespace
metadata:
  name: app
---  
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-app
  namespace: app
spec:
  hard:  
    requests.cpu: "1"  
    requests.memory: 1Gi  
    limits.cpu: "2"  
    limits.memory: 2Gi 
    persistentvolumeclaims: "4"
    pods: "4"
    replicationcontrollers: "4"
    secrets: "4"
    services: "1"

---  
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: app
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container
